global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "cadvisor"
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: "laravel_app"
    static_configs:
      - targets: ['laravel_app:9000']
  - job_name: "node_exporter"
    static_configs:
      - targets: ['172.17.0.1:9100']
